### ISSUE TITLE
OAUTH2 based SMART App Launch support

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#1127]
http://www.hl7.org/fhir/smart-app-launch/

Acceptance Criteria:  passing all relevant tests from either https://inferno.healthit.gov/inferno or https://inferno.healthit.gov/community

**Comment by lmsurpre** [comment]
We decided to use Keycloak as an external Authorization Server and we've both:
1. validated this support via inferno; and
2. tested this combination at the FHIR Connectathon 25

There remain some gaps, such as
1. the inferno test failures raised at https://keycloak.discourse.group/u/lmsurpre/activity
2. experience supporting user context (rather than patient context)
