### ISSUE TITLE
conditional delete operation with a match on multiple known valid resource instances

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#119]
Should return 200 instead of 412

https://touchstone.aegis.net/touchstone/scriptexecution?exec=201908231432318334944596&qn=/FHIR4-0-0-Advanced/Patient/05-delete/fhir-api-r4-patient-delete-03-conditional-multiple

**Comment by albertwang-ibm** [comment]
Looks like this an issue of the touchstone tool.

For test case DeleteConditionalMultipleMatchesJSON and DeleteConditionalMultipleMatchesXML, we returned 412 as required by fhir spec(http://hl7.org/fhir/R4/http.html#delete) because as advertised in our CapabilityStmt that our fhir server only supports DeleteConditionalSingleMatch.
So, Per my understanding, seems the tool should allow our server to pass the tests.
And from the conformance check info of the test execution, seems the tool knows that we don't support DeleteConditionalMultipleMatches, but seems the failures are still counted even after I turn on "Supported only in CapabilityStmt".

**Comment by albertwang-ibm** [comment]
I had sent email to touchstone support team, waiting for answer now...

**Comment by albertwang-ibm** [comment]
TouchStone confirmed that the failures are not counted in conformance report when "Supported in Capabstmt" is chosen.
