### ISSUE TITLE
Support token modifier ':of-type'

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#1323]
From http://hl7.org/fhir/search.html#token:

`:of-type` The search parameter has the format system|code|value, where the system and code refer to a Identifier.type.coding.system and .code, and match if any of the type codes match. All 3 parts must be present

From Team discussion:
1.  Must look at extracting the parameter values and supporting the identifiers (token,code,system)
1. Update logic to support search using those extracted values when of-type is used

**Comment by tbieste** [comment]
Since system + code + value must be extracted together, I don't think this can using the existing _TOKEN_VALUES_V table/view, so may require a schema change.

**Comment by lmsurpre** [comment]
I think we should be able to get this one without a schema change.  Two different ideas:

A.  Since the spec requires users of `of-type` to always query with all 3 components, we should be able to combine the Identifier.type `system+code` together into one string and use that as the "system" for a token value.  The one concern there is accidentally exceeding our column length limit, but I think it would be fine (if it exceeds the limit, you just can search on that field).

B.  Store the 3-tuple via an internal-only "composite parameter".
The parameter could be made of a couple components (both of type token): the first could have the system+code of the type and the second could have a default system and the identifier value as the code.

A worked example for B:
consider a Patient with an identifier that has 2 types:
```
Patient
Identifier
  Type 
    * mysystem|PI
    * yoursystem|ZZ
  Value 123
```

We'd have an internal search parameter definition like this
```
ibm-identifier-composite
  * ibm-identifier-type (token)
  * ibm-identifier-value (token) (always going to have the default system)
```

after extraction we'd have entries like this in PATIENT_TOKEN_VALUES:

param_code_id 	| 	system 	| 	value | comp_id
---- |  ---- | ---- | ---- |
ibm-identifier-type	| mysystem  	|PI  |	1
Ibm-identifier-value |	null |  		123  | 	1
ibm-identifier-type |  	mysystem |  	PI  | 	2
Ibm-identifier-value |  	null | 		123  |  	2



Query comes in:  Patient?identifier:of-type=mystem|PI|123

Interally re-written as:  Patient?identifier:of-type=mystem|PI$123

**Comment by tbieste** [comment]
Even though option A would be quicker, option B feels like the correct way to do this. Putting system+code into a single system field feels like a stop-gap approach.  Since ':of-type' is a modifier that is unique in that it basically treats the search parameter as a composite, I think special internal handling to treat it like a composite makes sense.
This can be done in 2 stages (in different PRs even across different sprints):
1)  Extract the parameter values (as an internal composite).
2)  Update search to handle ':of-type' to search for the internal composite.

**Comment by tbieste** [comment]
All right!  I think I have the :of-type search (as internal composite search) working. Thanks for the suggestion on that!
The FHIR spec says “All 3 parts must be present”, and that’s it.  But I wonder if consistency with how token normally works if fewer parts are provided would be nice.  Otherwise, what, throw an error?

**Comment by prb112** [comment]
@JohnTimm Verified
