### ISSUE TITLE
Conditional reference while processing transaction bundle 

### ISSUE THREAD

**Issue by sridhar-shivraj** [IBM/FHIR#1329]
**Is your feature request related to a problem? Please describe.**
When processing transactions, servers SHALL:
-check all references for search URIs
-For search URIs, use the search to locate matching resources
-if there are no matches, or multiple matches, the transaction fails, and an error is returned to the user
-if there is a single match, the server replaces the search URI with a reference to the matching resource

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
See "Conditional references" under https://www.hl7.org/fhir/http.html#trules

**Comment by prb112** [comment]
This is an enhancement request, I've moved the text to the formatted template.

**Comment by lmsurpre** [comment]
should benefit from #1353

**Comment by ibmatc** [comment]
I just discovered that after switching to FHIR 4.7.1 all of our Synthea-generated data no longer loads.  They are all being flagged as invalid because they use conditional references for the Practitioner field.  I have disabled validation for our use, but it would be appreciated if this were not necessary by supporting conditional references.

**Comment by prb112** [comment]
Hi @sridhar-shivraj The enhancement will be in version 4.8.0  Please let us know if you have any feedback.  We appreciate it.
