### ISSUE TITLE
Support for searching a token by codesystem, irrespective of the value ([system]|)

### ISSUE THREAD

**Issue by kathipavan** [IBM/FHIR#1409]
Hi Team, 
On the Conformance document (https://ibm.github.io/FHIR/Conformance/#searching-on-token) it is mentioned that "The IBM FHIR Server does not yet support searching a token by codesystem, irrespective of the value ([system]|)." . Could you please support this feature?

Thank you,
Pavan.

**Comment by tbieste** [comment]
Successfully verified via searches like these:

Patient?identifier:of-type=MR|12345 [FOUND]
Patient?identifier:of-type=mr|12345 [FOUND]
Patient?identifier:of-type=http://terminology.hl7.org/CodeSystem/v2-0203|MR|12345 [FOUND]
Patient?identifier:of-type=http://terminology.hl7.org/CodeSystem/v2-0203|mr|12345 [FOUND]
Observation?category=vital-signs [FOUND]
Observation?category=Vital-Signs [FOUND]
Observation?category=http://terminology.hl7.org/CodeSystem/observation-category|vital-signs [FOUND]
Observation?category=http://terminology.hl7.org/CodeSystem/observation-category|Vital-Signs [NOT FOUND, since CodeSystem is case-sensitive]
