### ISSUE TITLE
Evaluate local to external reference mapping in transaction Bundle processing

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1504]
**Describe the bug**
For bundles with bundleType == TRANSACTION, the FHIR server remaps certain local references to server-defined references as defined at https://www.hl7.org/fhir/bundle.html#bundle-unique

Evaluate this processing for efficiency as well as ensuring the remapping is correct and complete regardless of bundle order.
- We suspect that we may not be capturing ALL of the references before we start storing any of the resources.
- Because ordering is not deterministic we think we'll need to do a full pass before any of the processing happens.

For example, collecting the `urn:uuid` values from the POSTed resources and replacing the references in the PUT resources with those (or similar).

Consider refactoring the core processing so that it can be unit-tested thoroughly without requiring the server to be running.

**To Reproduce**
Load large bundles with different resource relationships.

**Expected behavior**
Bundle processing should be efficient and correct.

Specifically, we need a unit test for confirming the current behavior is correct or for adding detail of the bug to this issue.

**Additional context**
N/A

**Comment by michaelwschroeder** [comment]
Background on our current processing of local references in transaction bundles:
1. bundle entries can have a local reference specified in the Bundle.Entry.fullUrl field - the local reference must start with 'urn:'
2. for resources specified in POST and PUT requests, we look for reference fields containing references starting with 'urn:' and if they match a bundle entry local reference, we replace them with the actual resource reference of the resource in the bundle entry
3. we build a map of [local reference --> real resource reference] to enable the local reference resolution in the previous step. The map is built as follows:
    - after a POST request is processed, its [local ref --> real resource ref] mapping is added to the map (because it's only at that point that we know the logical ID the resource was created with)
    - after all POST resources have been processed, but before any PUT resources have been processed, all PUT [local ref --> real resource ref] mappings are added to the map (we can do this before processing because PUT requests are updates, so resources already have logical ID set)
4. processing order of requests is all POST requests first, then PUT requests

With current code, the following scenarios work:
1. any POST resource containing a local reference to a POST resource processed before it in the bundle will have the reference resolved properly because each POST resource has its mapping added to the map after being processed, meaning a mapping for a resource already processed will exist when a resource lower in the bundle is processed
2. any PUT resource containing a local reference to a POST resource will have the reference resolved properly because all POST resources will have their mappings added to the map before any PUT resources are processed
3. any PUT resource containing a local reference to another PUT resource will have the reference resolved properly because all PUT resources will have their mappings added to the map before any PUT resources are processed

With current code, the following scenarios fail:
1. any POST resource containing a local reference to a PUT resource will not have the reference resolved properly because the PUT resources will not have their mappings added to the map until after all POST resources have been processed
2. any POST resource containing a local reference to a POST resource below it in the bundle will not have the reference resolved properly because the POST resource lower in the bundle will not have its mapping in the map at the time the resource higher in the bundle is processed

Options to fix failing scenarios:
- Failing scenario 1 can be fixed simply by adding PUT resource mappings to the map before processing POST resources
- Failing scenario 2 I think can only be fixed by 'pre-allocating' logical IDs for resources to be created. This would allow the mappings to be added to the map before processing any POST resources, but would require that the logical ID be passed into and used by the persistence layer on resource creation.

Cases where mapping can't be added until after resource is processed:
1. On POSTs, there is a conditional create option based on the Bundle.Entry.Request.ifNoneExist field. A search query can be specified in that field, and if a single search result is found for that query, the POSTed resource is not created. Instead, the metadata for the search result will be returned, meaning that the logical ID could be different than a pre-allocated ID. So if that Bundle.Entry.Request.ifNoneExist field is populated, we wouldn't want to add a mapping before processing that resource.
2. On PUTs, there is a conditional update option based on the Bundle.Entry.Request.url field. A search query can be specified on the end of that url (i.e. Patient?_id=abc). If no search results are returned for the query AND if the resource ID is null, a create will be performed rather than an update, meaning we wouldn't know the logical ID until after the create. So if the Bundle.Entry.Request.url field contains a query string, we wouldn't want to add a mapping before processing that resource.

* For above cases, if we really wanted to support resolution of local references to them, we could execute the searches prior to fully processing the resources, just to get the logical ID for our mappings, but that seems expensive.

@punktilious , @prb112 , @lmsurpre , @JohnTimm  - thoughts as to how far we want to take this?

**Comment by michaelwschroeder** [comment]
After discussion, the following solution was agreed upon:
1. Utility to generate logical Ids (LogicalIdentityProvider interface class) will be moved to the fhir-persistence project, and a getLogicalId() interface will be added to the FHIRPersistence class. A default implementation is provided.
2. For transaction bundle processing, the FHIRRestHelper will 'pre-allocate' IDs for resources to be created using above getLogicalId() method, allowing for correct building of local reference map in following step.
3. FHIRRestHelper will build map of local references-->external references for all POST and PUT requests, excluding those specifying conditional create or update processing, before any requests are processed. This will address the failing scenarios documented in the previous comment.
4. When possible, local reference-->external reference mappings will also be added for conditional creates/updates as those bundle entry requests are processed, allowing for correct resolution of local references to those requests if the local reference is in a bundle entry processed after the conditional request.

**Comment by prb112** [comment]
PR is merged. Please close if appropriate
