### ISSUE TITLE
No schema files

### ISSUE THREAD

**Issue by kaklyugin** [IBM/FHIR#159]
Hi, guys!
Looks, there're no schemaddl  and createDB.sh files.
( Probably i did something wrong. I'vw insalled FHIR server, it works with DERBY, but i cannot connect it to DB2 , because there's no database schema)

1. Compile source code
2. Deploy to C:\liberty-runtime
3. Go to C:\liberty-runtime\wlp\bin
4. No <WLP_HOME>/fhir/bin/schemaddl  file
5. No <WLP_HOME>/fhir/bin/createDB.sh
6. No fhir.properties  file ( as far, as I understand, it is needed to generate schema)

**Expected behavior**
Files exist.

**Comment by prb112** [comment]
Related to [Update docs/FHIRServerUsersGuide.md for R4 #2 ](https://github.com/IBM/FHIR/issues/2)

The document is to be updated - https://github.com/IBM/FHIR/blob/master/docs/FHIRServerUsersGuide.md

**Comment by lmsurpre** [comment]
In the meantime we do have https://github.com/IBM/FHIR/blob/master/docs/DB2OnCloudSetup.md which covers setting up Db2 on Cloud...probably you could use that as we update the User Guide (which is more of an Administrators guide).  Pardon our dust...

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/371

**Comment by prb112** [comment]
The docs are updated, and the schema is posted to docs/schema. along with a SimpleSchemaPrinter updated to output the latest.

**Comment by lmsurpre** [comment]
I'm not sure that we want to put the DDL into our docs...it would be something we'd really need to commit to keeping up-to-date.  We'd need to be very diligent about updating docs with every schema update.

I think this issue was opened more because the User Guide was stale and pointing at our old fhir-schemaddl project (`<WLP_HOME>/fhir/bin/schemaddl` and `<WLP_HOME>/fhir/bin/createDB.sh`) and so I think the "fix" is to document how to use the fhir-persistence-schema project to accomplish these tasks.  https://github.com/IBM/FHIR/blob/master/docs/src/pages/guides/DB2OnCloudSetup.md is close, but it doesn't cover the initial database creation steps since those aren't needed with Db2 on Cloud.

I think we just need to document how to
1. create the database (we used to have shell script for this but its really not specific to our project); then
2. how to use `fhir-persistence-schema` to create and manage the schema. Everything we have on this today is at https://github.com/IBM/FHIR/tree/master/fhir-persistence-schema

**Comment by prb112** [comment]
I really see `fhir-persistence-schema` as insufficient for project consumers. There are two roles - database administrators and application administrators.  The creation of a schema using a third party tool is uncommon for third parties.  

There needs to be a reviewable artifact or a method to create the artifact as-is.  It's highly unlikely that the same people using the code are always administering the database. 

I'm OK with a how to.

**Comment by prb112** [comment]
Discussed with Lee in a code review and design discussion.  
We both agree how-to docs are the right way to go, as the tag is kept up to date.

**Comment by prb112** [comment]
QA complete.  #380 is a follow on to add dryrun functionality to the command structure.

**Comment by prb112** [comment]
Discussed with team.  @kaklyugin we'd be interested in your feedback. 
We do plan on adding a dryrun behavior. 

We'll close this at end of Sprint 4 (if no feedback).  [Nov 25]

**Comment by prb112** [comment]
Hi @kaklyugin please let us know your thoughts.

**Comment by prb112** [comment]
Marked as close at the end of Sprint 4
