### ISSUE TITLE
Search with no error or warning, just ignoring what I passed in on the search.

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1661]
**Describe the bug**
I sent a search like below to the FHIR server:  and it treated it as a patient read, and ignored the search parameters.  with no warning or error. 
fhir server should issue some error if you send information that is not understood. instead of just dropping it. 

**To Reproduce**
1. Start the IBM FHIR Server
2. Execute the request `[base]/Patient/[id]/?_lastUpdated=ge2020-11-02`

**Expected behavior**
If there is more data in an API call that is not understood. fhir should issue an error. 

**Additional context**
n/a

**Comment by prb112** [comment]
I don't see this as a bug, rather a feature.  I suggest an enhancement request, not a bug.

**Comment by lmsurpre** [comment]
I also think its more of a feature request than a bug.   The request is that we support "whole-system" search scoped to a particular compartment.  The desire is that:
* `[base]/Patient/[id]/ResourceType?param=value` searches for ResourceTypes within the patient compartment
* `[base]/Patient/[id]/?_lastUpdated=ge2020-11-02` search ALL resource types within the patient compartment

Note: overlaps with #264

**Comment by lmsurpre** [comment]
The idea on this one is just to emit some kind of message to indicate that we don't support searching across multiple resource types within a compartment ( #1658)

**Comment by tbieste** [comment]
Since there are no characters (except query parameters) after the final '/', the JAX-RS processing is sending this down the "read" code path, instead of the "search" code path, so the FHIR Server never even sees the final '/'.

One option is to add @Path("{compartment}/{compartmentId}/") to Search.java, so the "search" code path is invoked and will see that the resource type was not specified, and send the following error:
```
{
    "resourceType": "OperationOutcome",
    "id": "c0-a8-1-b-2a83384e-b3d8-446b-a557-d02fe5f409f3",
    "issue": [
        {
            "severity": "fatal",
            "code": "not-supported",
            "_code": {
                "extension": [
                    {
                        "url": "http://ibm.com/fhir/extension/not-supported-detail",
                        "valueCode": "resource"
                    }
                ]
            },
            "details": {
                "text": "'' is not a valid resource type."
            }
        }
    ]
}
```

**Comment by tbieste** [comment]
Updated the read operation to handle the _elements parameters (see https://www.hl7.org/fhir/http.html#read), and to return an error if any non-general search parameters are used -- instead of just ignoring them (or only returning an error if that are not a valid search parameter for searching that resource type).

**Comment by d0roppe** [comment]
Tested that we now see errors when adding search parameters to read statements.
