### ISSUE TITLE
Whole System Search with _type treating 'and' operator as an 'or' operator

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1718]
**Describe the bug**
This or search
[base]?_lastUpdated=2020-10-30&_type=Patient,Practitioner
Returns the same number of results as this and search.
[base]?_lastUpdated=2020-10-30&_type=Patient&_type=Practitioner
But the second search is an and search and a resource should not be both a patient and a practitioner.

**To Reproduce**

**Expected behavior**
This search should return a empty result set.
[base]?_lastUpdated=2020-10-30&_type=Patient&_type=Practitioner

**Additional context**

**Comment by tbieste** [comment]
While investigating this, I noticed a few things:

1)  The _type parameter values are OR'd together.  As an additional effect, the links (self, next, prev) don't match the original query.
2)  The _elements parameter values are OR'd together.  As an additional effect (self, next, prev) don't match the original query.
3)  The _sort, _count, _page, and _summary parameters values just pick the first value specified in the query. As an additional effect (self, next, prev) don't match the original query.

Option 1:
Just allow only one of each of these parameters on a query, which removes the confusion.

Option 2:
AND the values together.

**Comment by prb112** [comment]
Is Option 1 compliant with the specification? 
Option 2 - can you explain how this addresses the bug? And can you also pull the SQL so we can look at it?

**Comment by tbieste** [comment]
I've found any examples of _type, _elements, _sort, _count, _page, and _summary used multiple times in the same query.  It not explicitly stated, but each of these appears to be assumed as a single value.  So best I can tell are kind of compliant, but I don't think in the spirit of how the parameters are supposed to be used.

For option 2, I wasn't thinking the SQL wouldn't change, it would just find the intersection instead of the union of the values in parseQueryParameters(...) if multiples were provided.
But the more I think about it, perhaps picking the first value like _sort, _count, _page, and _summary would be the consistent thing to do for _type and _elements. The (self, next, prev) links returned only have a single value for these parameters anyway, so that more feels like the right approach.

Here's an example SQL:
SELECT RESOURCE_ID, LOGICAL_RESOURCE_ID, VERSION_ID, LAST_UPDATED, IS_DELETED, DATA, LOGICAL_ID  FROM (SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID  FROM (SELECT DISTINCT LR.LOGICAL_RESOURCE_ID, LR.LOGICAL_ID, LR.CURRENT_RESOURCE_ID FROM Practitioner_LOGICAL_RESOURCES LR ) AS LR  JOIN Practitioner_RESOURCES AS R  ON      R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID  AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  AND R.IS_DELETED = 'N' UNION ALL SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID  FROM (SELECT DISTINCT LR.LOGICAL_RESOURCE_ID, LR.LOGICAL_ID, LR.CURRENT_RESOURCE_ID FROM Patient_LOGICAL_RESOURCES LR ) AS LR  JOIN Patient_RESOURCES AS R  ON      R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID  AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  AND R.IS_DELETED = 'N') COMBINED_RESULTS ORDER BY LOGICAL_RESOURCE_ID ASC  OFFSET 0 ROWS  FETCH NEXT 10 ROWS ONLY

**Comment by tbieste** [comment]
After additional discussion, the current plan is:

1. If multiple parameters of _type, _elements, _sort, _count, _page, and _summary are specified on a search query:
    a. In strict mode: Return an error.
    b. In lenient mode: The first parameter value is used (which is currently the behavior for _sort, _count, _page, and _summary), log a message, and proceed.

2. If parameter _type is specified on a whole system search:
    a. In strict mode: Return an error.
    b. In lenient mode: Ignore the _type parameter, log a message, and proceed.

**Comment by tbieste** [comment]
Changes merged via:  https://github.com/IBM/FHIR/pull/1913

**Comment by d0roppe** [comment]
verified catching new failure.  also verified messages only end up in the trace file for lenient parsing.
