### ISSUE TITLE
FHIR Persistence schema updateSchema has a second call to the updateProc which shouldn't be necessary. 

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1781]
**Describe the bug**
FHIR Persistence schema updateSchema has a second call to the updateProc which shouldn't be necessary. 
The work is done twice needlessly, it'd be great to normalize this. 

Second, please also add timestamps to the stored procedures so we know when they were last updated  (this should be dropped into a comment at the top of the stored proc)

**Comment by tbieste** [comment]
Verified that "--update-schema" does not cause updateProcedures to be called, and "--update-proc" does cause updateProcedures to be called.

**Comment by tbieste** [comment]
I was able to verify that the procedures do get the updates applied for both “--update-schema” and “--update-proc”.  However, I wasn’t able to see anything about the “LOADED ON: {{DATE}}” comment on the DB server.  It looks like the comments at the top of .sql file are not included; perhaps need to move those comments within the procedure/function, instead of the very top of the file.

**Comment by prb112** [comment]
I think it's OK either way.  I only added them for debug purposes - with focus on db2 mainly

**Comment by tbieste** [comment]
ok, if it's for debug only, then I'll close this.  Thanks!
