### ISSUE TITLE
date search with =ap against a range is not finding the intersect when there is no end or no start date

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1877]
**Describe the bug**
A resource with a date as a range, and not having the end date for the range.  Searching that resource based on date=ap does not find the resource if the =ap does intersect the range. 

**To Reproduce**
1. Create a CarePlan resource with a "period": { "start": "2020-06-01"}
2. search CarePlan?date=ap2021-01-01T00:00:00.000Z
3. CarePlan is not found

**Expected behavior**
Care plan should be found because the search does intersect the range.

**Additional context**
n/a

**Comment by prb112** [comment]
Discussed with Lee and Dag
We want to relax the AND on the `ap` with a range and make it an OR

```
[1/21/21, 15:23:34:398 UTC] 000000f1 QuerySegmentA < com.ibm.fhir.persistence.jdbc.util.QuerySegmentAggregator buildCountQuery RETURN SqlQueryData [queryString=SELECT COUNT(DISTINCT R.LOGICAL_RESOURCE_ID)  FROM CarePlan_LOGICAL_RESOURCES LR  JOIN CarePlan_RESOURCES R ON R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  AND R.IS_DELETED = 'N'  JOIN CarePlan_DATE_VALUES  AS param0 ON (param0.PARAMETER_NAME_ID = 1122 AND (((param0.DATE_START >= ? AND param0.DATE_END <= ?)))) AND LR.LOGICAL_RESOURCE_ID = param0.LOGICAL_RESOURCE_ID JOIN CarePlan_TOKEN_VALUES_V  AS param1 ON ((param1.PARAMETER_NAME_ID = 1274 AND param1.TOKEN_VALUE = ? AND param1.CODE_SYSTEM_ID = 20009) OR (param1.PARAMETER_NAME_ID = 1282 AND param1.TOKEN_VALUE = ? AND param1.CODE_SYSTEM_ID = 20009)) AND LR.LOGICAL_RESOURCE_ID = param1.LOGICAL_RESOURCE_ID, bindVariables=[2021-01-30 23:08:21.4369141, 2021-02-03 03:15:38.5630615, abc-123-Patient, abc-123-Patient]]
```

Becomes (note the abbreviation to highlight the change)
```
 (param0.PARAMETER_NAME_ID = 1122 AND (((param0.DATE_START >= ? OR param0.DATE_END <= ?))))
```

We would update this in our conformance.md as well. 

The change is in this file `DateParmBehaviorUtil.java`

```
    public void buildApproxRangeClause(StringBuilder whereClauseSegment, List<Timestamp> bindVariables,
            String tableAlias, Instant lowerBound, Instant upperBound) {
        // @formatter:off
        whereClauseSegment
                .append(LEFT_PAREN)
                     .append(tableAlias).append(DOT).append(DATE_START).append(GTE).append(BIND_VAR)
                .append(AND)
                     .append(tableAlias).append(DOT).append(DATE_END).append(LTE).append(BIND_VAR)
                .append(RIGHT_PAREN);
        // @formatter:on
```

The intermediate AND would become OR

**Comment by lmsurpre** [comment]
I think the above was my suggestion, but it turns out to be too simplistic.
If we can assume that targetStart <= targetEnd and searchStart <= searchEnd (and I think we can), then it should be sufficient to do this:
`(targetStart <= searchEnd AND targetEnd >= searchStart)`

or equivalently:
`(targetEnd >= searchStart AND targetStart <= searchEnd)`

See https://stackoverflow.com/a/325964/161022 for the explanation.


Unfortunately, what the current code is doing is this:
`(targetStart >= searchStart AND targetEnd <= searchEnd)`
which is definitely not right.
We can fix it by either modifying to sequel or by changing the order of the bound variables

**Comment by lmsurpre** [comment]
related to https://github.com/IBM/FHIR/issues/1624 and https://github.com/IBM/FHIR/issues/1653

**Comment by tbieste** [comment]
Period fields have the following validation rule:  "per-1: If present, start SHALL have a lower value than end."

To cover the case where either period.start or period.end is not specified (but not both), something like this:

(targetEnd is null OR searchStart <= targetEnd)
   AND
(targetStart is null OR searchEnd >= targetStart)

I also will take a closer look at the other "range" prefixes (GE, GT, LE, LT, etc.), as I suspect they may also not be correctly handling Period fields with either start or end missing.

**Comment by tbieste** [comment]
After closer investigation and checking against the FHIR spec, http://hl7.org/fhir/search.html#prefix, here are my findings:

EQ: must fully overlap; matches current behavior
NE: does not fully overlap; matches current behavior
GT: any overlap; matches current behavior
LT: any overlap; matches current behavior
GE: any overlap; matches current behavior
LE: any overlap; matches current behavior
SA: no overlap; matches current behavior
EB: no overlap; matches current behavior
AP: any overlap; **does NOT match current behavior; current behavior must fully overlap, which is not possible if either start or end is not specified**

Summary:
Only AP needs to be changed to check for any overlap of the ranges, rather than a full overlap of the ranges.

**Comment by d0roppe** [comment]
verified that as soon as there is an overlap between the =ap and a date range the resource is returned using the 10% rule from the spec.
