### ISSUE TITLE
Support static configuration of external FHIR base URL (in favor of originalRequestUriHeader)

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1965]
**Is your feature request related to a problem? Please describe.**
The current implementation of the originalRequestUriHeader is a little more complicated than it should be.  we can pass in a full uri including search criteria, and the fhir server needs to figure out what it should replace.

**Describe the solution you'd like**
I propose that the use of the originalRequestUriHeader should expect the [base] part of a URI, and replace the [base] part of the result url's with the value entered no matter what was entered, as it is a user provided header for text replacement of the [base] part of the url only.  this will keep the code more simple and will result in predictable replacement. 

**Describe alternatives you've considered**
no change from current implementation

**Acceptance Criteria**
1.  If implemented test that only the [base] part of the result url is affected and is directly replaced with what is passed in on the header.

**Additional context**

**Comment by lmsurpre** [comment]
Suggestion is to continue supporting the current method which is to get this value from an incoming header IN ADDITION to this new method.
However, the two are a little different because the header will contain the full url (with or without query parameters) whereas this config option would be just the BASE url. (typically `https://host:port/fhir-server/api/v4` for us)

**Comment by d0roppe** [comment]
This is working using the "externalBaseUrl" and the text entered in the value is directly replaced.  So as long as you provide a valid [base] url it is working just fine.  Closing issue.
