### ISSUE TITLE
search by Patient.meta.extensions fails despite proper configuration and rebuild from source

### ISSUE THREAD

**Issue by jonathan-consensysHealth** [IBM/FHIR#2156]
**Describe the bug**
The IBM FHIR server has the ability [as documented](https://ibm.github.io/FHIR/guides/FHIRSearchConfiguration) for configuring the search options and index using your own search code.  Included in the documentation is sample 'favorite-color' example that creates a new SearchParameter resource and POST it to the [base]/SearchParameter endpoint.  Despite properly pushing and seeing it added, it fails to perform the search `[base]/Patient?favorite-color=pink` or [base]/Patient?favorite-color:exact=pink`.  

**To Reproduce**
1. created a new raw json file called `extension-search-parameters-color.json` (copied from IBM FHIR docs)

```
{
    "resourceType": "SearchParameter",
    "id": "Patient-favorite-color",
    "url": "http://ibm.com/fhir/SearchParameter/Patient-favorite-color",
    "version": "4.0.0",
    "name": "color",
    "status": "draft",
    "experimental": false,
    "date": "2018-12-27T22:37:54+11:00",
    "publisher": "IBM FHIR Server Test",
    "contact": [{
            "telecom": [{
                    "system": "url",
                    "value": "http://ibm.com/fhir"
            }]
    },
    {
            "telecom": [{
                    "system": "url",
                    "value": "http://ibm.com/fhir"
            }]
    }],
    "description": "the patient's favorite color",
    "code": "favorite-color",
    "base": ["Patient"],
    "type": "string",
    "xpathUsage": "normal",
    "xpath": "f:Patient/f:extension[@url='http://ibm.com/fhir/extension/Patient/favorite-color']/f:valueString",
    "expression": "Patient.extension.where(url='http://ibm.com/fhir/extension/Patient/favorite-color').valueString",
    "multipleOr": true,
    "multipleAnd": true,
    "modifier": []
}
```

2.  POST this file to FHIR server. 
`curl -v -k -u$FHIR_CREDS -X POST --header "Content-type: application/fhir+json" -d @extension-search-parameters-color.json https://localhost:9443/fhir-server/api/v4/SearchParameter`

3. Add new patient with this extension to Patient Resource:
``` 
{ "resourceType" : "Patient", ... 
 "extension": [
    {
      "url": "http://ibm.com/fhir/extension/Patient/favorite-color",
      "valueString": "pink"
    }, ... 
}
```

4. Reindex

`curl -s -k -u$FHIR_CREDS -X POST https://localhost:9443/fhir-server/api/v4/Patient/$reindex`

**Expected behavior**
- find patient by favorite-color

***Actual behavior***
```
{
  "resourceType": "Bundle",
  "id": "5e2dbe31-b5e9-477e-9167-409e65f9992d",
  "type": "searchset",
  "total": 0,
  "link": [
    {
      "relation": "self",
      "url": "https://localhost:9443/fhir-server/api/v4/Patient?_count=10&favorite-color=pink&_page=1"
    }
  ]
}
```

**Additional context**
I've also hard coded this SearchParameter into the build scripts/config, re-=built from scratch and `no Joy`.  

Is there something that I am missing and/or missing from the documentation to properly configure `search by custom extension` that I need to do?  or is this a bug?

**Comment by prb112** [comment]
Hi @jonathan-consensysHealth 

The IBM FHIR Server is multi-tenant - the extension-search-parameters.json is stored with the tenant specific configuration as described in https://ibm.github.io/FHIR/guides/FHIRSearchConfiguration/#11-tenant-specific-parameters 

When you configure the extension-search-parameters ( such as the above SearchParameter), existing resources must be reindexed in order to be picked up in the search. https://ibm.github.io/FHIR/guides/FHIRSearchConfiguration#2-re-index

References to dynamic registry applies to implementation guides, and the parameter `fhirServer/core/serverRegistryResourceProviderEnabled` must be true if you are posting SearchParameters. 

```
fhirServer/core/serverRegistryResourceProviderEnabled | boolean | Indicates  whether the server registry resource provider should be used by the  FHIR registry component to access definitional resources through the  persistence layer.
-- | -- | --
```

**Comment by jonathan-consensysHealth** [comment]
yep, I think this seems to be enabled even without recompiling, but using the default docker config and default tenant: 
```
docker run -it -d -p9443:9443 -e BOOTSTRAP_DB=true ibmcom/ibm-fhir-server

... steps 1-4 above... 

docker exec -it 88da428ac947 /bin/cat ./config/default/fhir-server-config.json | jq '.fhirServer .core .serverRegistryResourceProviderEnabled' 
> true 
```

**Comment by lmsurpre** [comment]
Its maybe a bit confusing... `serverRegistryResourceProviderEnabled` *does* make the dynamically-pushed SearchParameter resources available in our internal FHIR-registry.   However, we don't actually use this registry for deciding which search parameters to use during extraction or search.  So its really moot when it comes to extending the server's search behavior.

*Instead* you must follow https://ibm.github.io/FHIR/guides/FHIRSearchConfiguration/#11-tenant-specific-parameters to make your `extension-search-parameters.json` available to the server in a way that it will actually use them.

There are 2 reasons for this: 
1.  Our extended search parameter support predates the existence of our `fhir-registry` and we just havn't gotten to this yet.   #1596 is the placeholder for that.
2.  Loading the core set of search parameters during startup (vs storing them in the db as resources) means we can avoid computing them each time.
  * See #1625 for more information / considerations on that.
  
It should be possible for us to enable this, but its not clear to me that it provides much benefit.  Dynamically changing the search parameters is costly because, as paul mentions, it requires a reindex after each change (and reindex is expensive if you have lots of data).
In every use case we've hit to date, it hasn't been a problem to configure the search parameters a priori via this `extension-search-parameters.json` config file.

Please let us know if this more-static config approach doesn't work for you for some reason.

Also, if you get a chance, please let us know what led you to believe that you can POST SearchParameter resources to the server and have it automatically pick those up.  If we imply that works somewhere, I'd like to squash that so that we can avoid any confusion in the future.

**Comment by jonathan-consensysHealth** [comment]
You are correct my initial POST to [base]/SearchParameter did not work.  but returns: 

```
{
  "resourceType": "OperationOutcome",
  "id": "ac-11-0-3-641ec8fa-f954-4902-87a6-5e249d4a1f37",
  "issue": [
    {
      "severity": "fatal",
      "code": "invalid",
      "details": {
        "text": "Search parameter 'favorite-color' for resource type 'Patient' was not found."
      },
      "expression": [
        "<empty>"
      ]
    }
  ]
}

```

after that, I did try adding the searchParameter to the default `extension-search-parameters.json` and even restarted the docker container.  


and it is there: 

```
docker exec -it 95472b3f1b5f /bin/cat ./config/default/extension-search-parameters.json | jq '.entry[0]' | jq 
```
yields: 
```
{
  "fullUrl": "http://ibm.com/fhir/SearchParameter/Patient-favorite-color",
  "resource": {
    "resourceType": "SearchParameter",
    "id": "Patient-favorite-color",
    "url": "http://ibm.com/fhir/SearchParameter/Patient-favorite-color",
    "version": "4.0.0",
    "name": "favorite-color",
    "status": "draft",
    "experimental": false,
    "date": "2018-12-27T22:37:54+11:00",
    "publisher": "IBM FHIR Server Test",
    "contact": [
      {
        "telecom": [
          {
            "system": "url",
            "value": "http://ibm.com/fhir"
          }
        ]
      },
      {
        "telecom": [
          {
            "system": "url",
            "value": "http://ibm.com/fhir"
          }
        ]
      }
    ],
    "description": "the patient's favorite color",
    "code": "favorite-color",
    "base": [
      "Patient"
    ],
    "type": "string",
    "xpathUsage": "normal",
    "xpath": "f:Patient/f:extension[@url='http://ibm.com/fhir/extension/Patient/favorite-color']/f:valueString",
    "expression": "Patient.extension.where(url='http://ibm.com/fhir/extension/Patient/favorite-color').valueString",
    "multipleOr": true,
    "multipleAnd": true
  }
}
```

then trying: 
```
curl -k -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/Patient?favorite-color=pink' | jq 
```

not found, but at least no error on search by color as above using POST to SearchParameter approach above: 
```
{
  "resourceType": "Bundle",
  "id": "4acbed33-08ca-45cb-a04a-fb2b2c4fc4e0",
  "type": "searchset",
  "total": 0,
  "link": [
    {
      "relation": "self",
      "url": "https://localhost:9443/fhir-server/api/v4/Patient?_count=10&favorite-color=pink&_page=1"
    }
  ]
}
```

**Comment by lmsurpre** [comment]
Thanks for the great detail; I think I see the issue.  We use the “expression” of the SearchParameter to extract the value from the resource during create/update.

Above your SearchParameter has:

‘Patient.extension.where(url='http://ibm.com/fhir/extension/Patient/favorite-color').valueString‘

Instead, I think the proper FHIRPath would be:
‘Patient.extension.where(url='http://ibm.com/fhir/extension/Patient/favorite-color').value’

Or possibly 
‘Patient.extension.where(url='http://ibm.com/fhir/extension/Patient/favorite-color').value.as(String)’ if you want to ensure only string values are extracted.

Please give it a try and confirm this does the trick.  Also, if you happened to get that example from our docs, I’d love to get that cleaned up.

**Comment by lmsurpre** [comment]
@jonathan-consensysHealth did the above work for you?  Assuming so, I'll plan to close this issue later today if we don't hear back.  Thanks and keep 'em coming.

**Comment by prb112** [comment]
Per Lee's comment yesterday, we'll close this.  Please re-open or create a new issue should it be appropriate.

**Comment by jonathan-consensysHealth** [comment]
yep, confirmed...  no bug... i suppose it is a 'feature' then.  

Was able to enable this by appending the favorite-color searchParameter example to the entry array under the [default tenant extension-search-parameter.json file](https://github.com/IBM/FHIR/blob/main/fhir-server/liberty-config/config/default/extension-search-parameters.json)  then building from source.
