### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by rubberduck203** [IBM/FHIR#2266]
**Describe the bug**

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.ibm.fhir.model.util.XMLSupport (file:/Users/rubberduck/.gradle/caches/modules-2/files-2.1/com.ibm.fhir/fhir-model/4.7.0/706afb6278d6bf5e56dec035ea17a0f326f41bba/fhir-model-4.7.0.jar) to constructor com.sun.xml.internal.stream.XMLInputFactoryImpl()
```

**Environment**
Which version of IBM FHIR Server?

`4.7.0`

**To Reproduce**

I'm not entirely sure.
Would be happy to help reproduce it given some guidance.

I'm running OpenJDK 11 and it seems that this behavior was introduced in JDK 9.
If you're using an older JDK, you might not see this.

**Expected behavior**

No warnings.

**Additional context**

This StackOverflow Q&A may help someone who understands the problem better than I.
https://stackoverflow.com/questions/50251798/what-is-an-illegal-reflective-access

**Comment by prb112** [comment]
Thanks @rubberduck203 we're aware of the warning.  It's related to the XML library which we is dependent upon uses Reflection to access the xml model in memory.

**Comment by rubberduck203** [comment]
Cool. Thanks @prb112.
I didn't see an issue anywhere, so wanted to make sure you were aware.

**Comment by JohnTimm** [comment]
We are currently using the JVM default implementations of `XMLInputFactory`, `XMLOutputFactory`, and `TransformerFactory`: `com.sun.xml.internal.stream.XMLInputFactoryImpl`, `com.sun.xml.internal.stream.XMLOutputFactoryImpl`, and `com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl` respectively. We found that other, 3rd party implementations cause problems with how we parse / generate XML. I recently retested using Woodstox, Xalan-J, and Saxon without issues. For this particular issue, I think we should upgrade to Java 9 first and then see where things stand. If it turns out that we need to move to a different implementation to avoid the reflective access warning, then we can decide to do so at that time.

**Comment by rubberduck203** [comment]
Just FYI, as of Java 17, this won't even compile anymore.
The 17 LTS is scheduled for release Sept 2021.

**Comment by prb112** [comment]
Confirmed with JDK 11 it no longer is reported.

Test 1: Ran build with 4.9.1 and main

```
mvn clean install -f fhir-parent -pl ../fhir-model --am
```

Confirmed the message exists on the tag, and not in the main. 

Test 2: Ran with Liberty on AdoptOpenJDK 11 with 4.9.1 and main 

Confirmed the message exists on tag and not in the main branch
