### ISSUE TITLE
Token search with case-insensitive code system failing when common_token_value_id for system+code previously stored with case-sensitive code

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#2308]
In my local Eclipse environment, pulled the latest changes to FHIR main and rebuilt.
Ran FHIR Integration Tests ... 9 of them failed.
All were specific to token search where you specify both system and code and the system is case-insensitive and the code does not match its normalized code value (i.e. code contains uppercase characters)

Expected all tests to pass.

**Comment by kmbarton423** [comment]
![failingTests](https://user-images.githubusercontent.com/69682345/116754370-9b633e00-a9d6-11eb-874d-af601f2301ca.png)

**Comment by d0roppe** [comment]
This only happens if there is already data in the DB, with a new Derby DB this does not reproduce.

**Comment by michaelwschroeder** [comment]
If a token value which specifies a case-insensitive code system and a code which contains uppercase characters has been indexed prior to changes made for issue #1551 and stored in the common_token_values table, then on a subsequent resource creation and search specifying the same system+code after the 1551 changes, the resource will not get returned as a match, even though it should. This is due to a bug in how the common_token_value_id is being retrieved - it should be trying to retrieve based on the normalized code value for a case-insensitive code system, but it is using the code value unmodified. This results in the wrong common_token_value_id being used in the search query, thus no match.

**Comment by kmbarton423** [comment]
Ran the following to confirm behavior:
1. create a code system which is caseSensitive=true and contains a code that contains uppercase characters
2. create resource#1 so system+code combo gets stored in common_token_value_id table
3. update the code system to caseSensitive=false
4. create resource#2 using same system+code as resource#1 
5. search for all resources using system+code -> found only resource#2
6. updated resource#1 to trigger reindex
7. search for all resources using system+code -> found both resource#1 and resource#2
