### ISSUE TITLE
Concurrent updates to the same resource can result in lost updates

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2405]
**Describe the bug**
Concurrent updates to the same resource are not behaving as expected.
For each update interaction, the IBM FHIR Server rest layer performs a read followed by an update.

My belief was that, in case of concurrent updates to the same resource, the server would pick a winner and reject the other request(s) with an HTTP 409 Conflict status  (it used to work this way in DSTU2 days).

However, after running some tests, this doesn't seem to be working in the latest server (or probably any version since we open-sourced the project).

**Environment**
IBM FHIR Server with PostgreSQL

**To Reproduce**
1. launch a (e.g. via `docker-compose up -d` from the demo dir)
2. execute the ConcurrentUpdateTest under fhir-server-test (`com.ibm.fhir.server.test.db2`)

Note that it fails.

3. enable request/response logging in test.properties and run again

Note that multiple responses come back with the same version number (meaning we've lost some).

**Expected behavior**
If a resource version changes in-between the before-update read and the actual call to save_any_resource, then we should NOT commit and instead we should return an appropriate error that indicates the update was not performed.

**Additional context**
We do support the `If-Match` for avoiding the "lost updates" problem (as described at https://www.hl7.org/fhir/http.html#concurrency).
However, this requires clients to read / keep track of the previous version on their end.
Further, because the check is performed in the REST layer against the version we read BEFORE the update, it is still technically possible for the resource to change between that read and the actual call to save_any_resource.

It might be possible to avoid this if we are able to either remove the before-update read OR turn that read into a "SELECT FOR UPDATE" (although this doesn't work for the initial create-on-update of the resource).

**Comment by punktilious** [comment]
The check to catch the version conflict was a relatively simple fix. Cleaned things up a bit because for this implementation there's no need to support an asserted version id (which might not be the latest version id - useful for logical replication). However the fix did expose a deadlock scenario for Derby cause by the default isolation level being TRANSACTION_REPEATABLE_READ. This resulted in shared locks lingering on rows which were selected when reading the current version of the resource. In Derby, these locks are not compatible with the exclusive lock requested by the UPDATE xx_logical_resources statement. The resulting deadlock graph looks something like this:
```
A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, LOGICAL_RESOURCES, (115,11)
  Waiting XID : {74421, U} , APP, SELECT logical_resource_id FROM logical_resources WHERE resource_type_id = ? AND logical_id = ? FOR UPDATE WITH RS
  Granted XID : {74409, U}
Lock : ROW, PATIENT_LOGICAL_RESOURCES, (8,29)
  Waiting XID : {74409, X} , APP, UPDATE Patient_logical_resources SET current_resource_id = ?, is_deleted = ?, last_updated = ?, version_id = ? WHERE logical_resource_id = ?
  Granted XID : {74401, S} , {74416, S} , {74409, S} , {74421, S}
. The selected victim is XID : 74421.
```

The solution is to set the isolation level for Derby datasources in openliberty:

```
     <dataSource id="fhirDatasourceBootstrapDefaultDefault" jndiName="jdbc/fhir_default_default" type="javax.sql.XADataSource" statementCacheSize="200" syncQueryTimeoutWithTransactionTimeout="true" isolationLevel="TRANSACTION_READ_COMMITTED">
        <jdbcDriver javax.sql.XADataSource="org.apache.derby.jdbc.EmbeddedXADataSource" libraryRef="fhirSharedLib"/>
            <properties.derby.embedded createDatabase="create" databaseName="derby/fhirDB"/>
        <connectionManager maxPoolSize="50" minPoolSize="10"/>
    </dataSource>
```

As part of the effort to uncover the deadlock, the stored procedure implementations were simplified by removing an update on xx_logical_resources when the resource was new. The new solution allocates the resource_id early and uses it to set the xx_logical_resources.current_resource_id column before the actual resource row is created. This should be particularly helpful for PostgreSQL, because it avoids creating a tombstone which then needs to be vacuumed.

**Comment by lmsurpre** [comment]
I ran our ConcurrentUpdateTest against a local postgresql database and confirmed that with the changes for 4.8.2 that this issue is addresed on Postgresql.
@prb112 did the same on a local Db2.

For the Derby-specific issue we have opened #2420
