### ISSUE TITLE
Server Integration Tests fail when Derby has too much data

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#262]
Derby after a period of time up and running accumulates enough data to slow the Bundle tests.  These tests may return too much data before the transaction timeout finishes (or the timeout reaches a point during a derby operation to fail). 

**Steps to replicate issue**
- Stop the Liberty Server
- Wipe Apache Derby directory in the server folder
- Start the Liberty Server
- Once the server is up and operational (the db is deployed) 
    - Run the Server Integration Tests ` mvn clean package -f fhir-server-test/pom.xml -DskipTests=false`
    - Until you hit the following error

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   BundleTest.testBatchConditionalDeletes:2280->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testBatchDeletes:1956->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testBatchLocalRefs3:1656->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testBatchUpdateCreates:698->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testBatchUpdates:498->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testBatchUpdatesVersionAware:532->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testTransactionConditionalDeletes:2391->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testTransactionDeletes:2046->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testTransactionUpdateCreates:1338->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testTransactionUpdates:1114->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[ERROR]   BundleTest.testTransactionUpdatesVersionAware:1155->FHIRServerTestBase.assertResponse:422 expected:<200> but was:<500>
[INFO]
[ERROR] Tests run: 289, Failures: 11, Errors: 0, Skipped: 20
```

**Notes**
This may require 'enough' data in the system or be more sophisticated.

**Comment by lmsurpre** [comment]
We should confirm whether the same issue exists in Db2 or not...maybe its just a Derby issue?

Probably not due to the number of JOINs being generated.

**Comment by albertwang-ibm** [comment]
We found testSearchPatientWithBaseParametersAndExtensions of SearchExtensionTest can easily time out if there are about 50 patient created before the test. After studying the query plan logs of derby, I found that this is caused by the bad sqlquery generated by our QureyBuild.
**The Sqlquery generated by the querybuild:**
SELECT COUNT(R.RESOURCE_ID) 
  FROM 
APP.Patient_RESOURCES R JOIN APP.Patient_LOGICAL_RESOURCES LR ON R.LOGICAL_RESOURCE_ID=LR.LOGICAL_RESOURCE_ID AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  
JOIN APP.Patient_STR_VALUES P1 ON P1.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID 
JOIN APP.Patient_STR_VALUES P2 ON P2.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID 
JOIN APP.Patient_NUMBER_VALUES P3 ON P3.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID 
JOIN APP.Patient_TOKEN_VALUES P4 ON P4.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID 
JOIN APP.Patient_STR_VALUES P5 ON P5.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID 
JOIN APP.Patient_QUANTITY_VALUES P6 ON P6.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID 
  WHERE 
R.IS_DELETED <> 'Y' 
AND P1.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID 
AND (P1.PARAMETER_NAME_ID=5 AND (P1.STR_VALUE_LCASE LIKE ? ESCAPE '+')) 
AND P2.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID 
AND (P2.PARAMETER_NAME_ID=14 AND (P2.STR_VALUE_LCASE LIKE ? ESCAPE '+')) 
AND P3.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID 
AND (P3.PARAMETER_NAME_ID=15 AND (P3.NUMBER_VALUE = ?)) 
AND P4.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID 
AND (P4.PARAMETER_NAME_ID=16 AND ((P4.TOKEN_VALUE = ?))) 
AND P5.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID 
AND (P5.PARAMETER_NAME_ID=18 AND (P5.STR_VALUE LIKE ? ESCAPE '+')) 
AND P6.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID 
AND (P6.PARAMETER_NAME_ID=19 AND ((P6.QUANTITY_VALUE = ? AND P6.CODE = ?))) 
**The problem:**
(1) redundant filters like P#.LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID in Where, which are already added in the On condition of the Join.
(2) the Joins creates huge temp table with numerous rows in it, with 1 patient created and then run the query, a temp table of about 4000 rows were created before the filtering defined in Where. with about 140 patients created, I found tens of million rows were created in the temp table. which caused high usage of both cup and memory and finally caused the timeout of the request.
* please noticed that, some DB engines do can optimize the conditions defined in Join On and Where before it's executed, but this is obviously not true for derby in this case.  
**The solution:**
We are going to optimize the querybuild to generate sqlquery like this following to make sure the temp table is much much more smaller and make sure the query is more efficient.
SELECT COUNT(R.RESOURCE_ID) 
  FROM 
APP.Patient_RESOURCES R JOIN APP.Patient_LOGICAL_RESOURCES LR ON R.LOGICAL_RESOURCE_ID=LR.LOGICAL_RESOURCE_ID AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID AND R.IS_DELETED <> 'Y'  
JOIN APP.Patient_STR_VALUES P1 ON P1.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID AND (P1.PARAMETER_NAME_ID=5 AND (P1.STR_VALUE_LCASE LIKE ? ESCAPE '+'))
JOIN APP.Patient_STR_VALUES P2 ON P2.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID AND (P2.PARAMETER_NAME_ID=14 AND (P2.STR_VALUE_LCASE LIKE ? ESCAPE '+'))
JOIN APP.Patient_NUMBER_VALUES P3 ON P3.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID AND (P3.PARAMETER_NAME_ID=15 AND (P3.NUMBER_VALUE = ?)) 
JOIN APP.Patient_TOKEN_VALUES P4 ON P4.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID AND (P4.PARAMETER_NAME_ID=16 AND ((P4.TOKEN_VALUE = ?)))
JOIN APP.Patient_STR_VALUES P5 ON P5.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID AND (P5.PARAMETER_NAME_ID=18 AND (P5.STR_VALUE LIKE ? ESCAPE '+'))
JOIN APP.Patient_QUANTITY_VALUES P6 ON P6.LOGICAL_RESOURCE_ID=R.LOGICAL_RESOURCE_ID AND (P6.PARAMETER_NAME_ID=19 AND ((P6.QUANTITY_VALUE = ? AND P6.CODE = ?)))
