### ISSUE TITLE
db2: common_token_values constraint violation

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2634]
**Describe the bug**

[ERROR   ] INSERT INTO common_token_values (mt_id, token_value, code_system_id)      SELECT FHIR_ADMIN.sv_tenant_id, v.token_value, v.code_system_id FROM      (VALUES (CAST(? AS VARCHAR(1024)),CAST(? AS INT)), (CAST(? AS VARCHAR(1024)),CAST(? AS INT)) ) AS v(token_value, code_system_id)  LEFT OUTER JOIN common_token_values ctv               ON ctv.token_value = v.token_value              AND ctv.code_system_id = v.code_system_id       WHERE ctv.token_value IS NULL ; [{17ad0a468df-70533aad-4fab-47bc-8536-8e817fb7b3c7,20038}, {active,20079}]
One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "2" constrains table "FHIRDATAZ.COMMON_TOKEN_VALUES" from having duplicate values for the index key.. SQLCODE=-803, SQLSTATE=23505, DRIVER=4.28.11

**Environment**
Which version of IBM FHIR Server?
4.8.3

**To Reproduce**
1. Go to 'Create  two  identical bundles
2. Create two threads
3. Push at same time with  same COMMON_TOKEN_VALUES
You'll hit the above constraint  violation

**Expected behavior**
Should retry and not  faili.

**Additional context**

**Comment by punktilious** [comment]
Marking the transaction for retry and the exception as retryable will allow the reindex retry mechanism to handle this inside the server without emitting the error, as implemented. However, the issue is still present for normal ingestion calls (PUT/POST) because we don't have a tx retry mechanism in place there (yet). This can be addressed under issue #2664 which will retry the statement locally but in a loop so as to catch the error for multiple threads, not just 2.
