### ISSUE TITLE
Add support for a pattern value constraint with the Coding data type

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2651]
The `ConstraintGenerator` class does not currently support pattern value constraints when the data type is `Coding`

**Comment by lmsurpre** [comment]
I worked with John to identify a constraint from US Core v4 that showed this validation gap.

Specifically, it has a slice definition like the following:
```
    {
        "id" : "Observation.code.coding",
        "path" : "Observation.code.coding",
        "slicing" : {
          "discriminator" : [
            {
              "type" : "pattern",
              "path" : "$this"
            }
          ],
          "rules" : "open"
    },
```

with two slices:
* coding:PulseOx (59408-5)
* coding:O2Sat (2708-6)

I loaded this structure definition to my server and posted an observation that claims conformance to this profile.

This one worked fine:
```
"coding" : [
    {
    "system" : "http://loinc.org",
    "code" : "2708-6",
    "display" : "Oxygen saturation in Arterial blood"
    },
    {
    "system" : "http://loinc.org",
    "code" : "59408-5",
    "display" : "Oxygen saturation in Arterial blood by Pulse oximetry"
    },
    {
    "system" : "urn:iso:std:iso:11073:10101",
    "code" : "150456",
    "display" : "MDC_PULS_OXIM_SAT_O2"
    }
]
```

I then confirmed that omitting either of slices results in a constraint violation like the following (which makes sense because both of them have a cardinality of 1..1):
```
        {
            "severity": "error",
            "code": "invariant",
            "details": {
                "text": "generated-us-core-pulse-oximetry-2: Constraint violation: code.exists() and code.all(coding.where(system = 'http://loinc.org' and code = '59408-5').count() = 1 and coding.where(system = 'http://loinc.org' and code = '2708-6').count() = 1 and memberOf('http://hl7.org/fhir/us/core/ValueSet/us-core-vital-signs', 'extensible'))"
            },
            "diagnostics": "Caused by: [[expression: coding.where(system = 'http://loinc.org' and code = '2708-6').count() = 1, result: false, location: Observation.code]]",
            "expression": [
                "Observation"
            ]
        },
```

I think this is working as desired although I'm not 100% what the behavior was before this change.

**Comment by JohnTimm** [comment]
The behavior before the change was that we did not generate a constraint for `type=pattern` and `path=$this` and now we do. I think this issue can be closed.
