### ISSUE TITLE
Fix Date/Time related issues found in FHIRPath spec test results

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#388]
A number of failures are related to date/time parsing and processing

**Comment by JohnTimm** [comment]
Fixed in #446

**Comment by lmsurpre** [comment]
We went back through and added comments to the datetime-related tests that we are skipping.
In most cases, we believe these to be test case issues.

However, in the case of one, `testLiteralTimeUTC`, it is a [minor] bug in our fhirpath parser.
Specifically, ANTLR has an error recovery mechanism which allows it to "recover" the parse, even with a single bad char.
This strategy leads us to strip off the 'Z' in the literal, rather than report it as an error.

We investigated this for a while, but did not find an easy fix and so we have no plan to fix this at this time.
