### ISSUE TITLE
Support for searching references by identifier

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#773]
From https://www.hl7.org/fhir/search.html#reference:
> References are also allowed to have an identifier. The modifier :identifier allows for searching by the identifier rather than the literal reference:

> GET [base]/Observation?subject:identifier=http://acme.org/fhir/identifier/mrn|123456
> This is a search for all observations that reference a patient by a particular patient MRN. When the :identifier modifier is used, the search value works as a token search. The :identifier modifier is not supported on canonical elements since they do not have an identifier separate from the reference itself.

> Chaining is not supported when using the :identifier modifier, nor are chaining, includes or reverse includes supported for reference elements that do not have a reference element.

**Comment by lmsurpre** [comment]
We think we're already handling the extraction side of this one, so it should be just a matter of updating our query generator to look in the TOKEN_VALUES_V view with the identifier system+value instead of the reference value.

**Comment by lmsurpre** [comment]
Currently, we don't even extract the identifier field of reference elements, so that would be step 1.

**Comment by tbieste** [comment]
As far as I can tell:
Observation?patient:identifier=http://acme.org/fhir/identifier/mrn|123456
is (from the end-user's perspective) functionally the same as:
Observation?patient.identifier=http://acme.org/fhir/identifier/mrn|123456

Unless the identifier search parameter should always be extracted, rather than only if the "identifier" search parameter is defined for the Patient resource type (in this example), then I think the necessary values are already being extracted.

**Comment by prb112** [comment]
Completed QA. Looks good and behaved as expected.
